print("____________________")
print("King of Demons might even work some day!")
print("Let the coding errors begin!")
print("____________________")
print("What erors i dont kno how to maek errers")